### ISSUE TITLE
badges.json returns users

### ISSUE THREAD

**Issue by seVladimirs** [SAP-samples/sap-community-activity-badges#14]
@jung-thomas seems like with this commit https://github.com/SAP-samples/sap-community-activity-badges/commit/6029d3a3936cd3e72dcb5d3b328ccbcd5b0ada8d you've pushed users into badges.json

**Comment by jung-thomas** [comment]
That's what I deserve for rushing around before I travel. 🫢 I'll fix that as soon as I land in Germany in the morning. Thanks.

**Comment by jung-thomas** [comment]
Fixed now thanks to Airport WiFi.

**Comment by marianfoo** [comment]
Thanks @jung-thomas , was wondering what was wrong with my checker as well 😃
Enjoy your time in Germany!
