### ISSUE TITLE
links to examples are broken

### ISSUE THREAD

**Issue by larshp** [SAP-samples/sap-community-activity-badges#3]
in the readme, 

```
Example: [/showcaseBadges/your.SCN.ID](/showcaseBadges/your.SCN.ID)
```

this links to https://github.com/SAP-samples/sap-community-activity-badges/blob/main/showcaseBadges/your.SCN.ID which is a 404

should this link to https://devrel-tools-prod-scn-badges-srv.cfapps.eu10.hana.ondemand.com/showcaseBadges/your.SCN.ID instead?

is `devrel-tools-prod-scn-badges-srv.cfapps.eu10.hana.ondemand.com` a server that will keep running?

**Comment by jung-thomas** [comment]
Actually it's a relative URL on purpose. We use the README.md as the source content of the root of the service when running:
https://devrel-tools-prod-scn-badges-srv.cfapps.eu10.hana.ondemand.com/

It's also designed so if people wanted they could fork, adapt, reuse, and then deploy the service on their own account.  The relative URL in the README would then still work.

https://github.com/SAP-samples/sap-community-activity-badges/blob/main/srv/routes/intro.js#L12

**Comment by jung-thomas** [comment]
Although the activity cards are something we will detail more in about two weeks. They will go along with another surprise element of Devtoberfest that isn't quite ready yet.

**Comment by jung-thomas** [comment]
Although I get what you are seeing since we reused the same content on the project readme. I will do some cleanup there this afternoon to be a more holistic README for the whole project.  I missed that on my to-do list. But full details on the whole project will have to wait until the above mentioned surprise. ;)

**Comment by larshp** [comment]
no worries, just stumbled across it 😄

**Comment by jung-thomas** [comment]
I am curious since you were looking around in the repo; did you already find the @larshp specific Easter Egg?

**Comment by larshp** [comment]
I didnt read any of the code/files, but now I will look through it :)

**Comment by larshp** [comment]
found it, yiiiha
