### ISSUE TITLE
Week 3 missing 

### ISSUE THREAD

**Issue by bmaciag** [SAP-samples/sap-community-activity-badges#6]
Hi @jung-thomas 
will there be an update for the Badges/Points for week 3?
Best, Bartho

**Comment by jung-thomas** [comment]
The gameboard was updated yesterday afternoon with Week 3

**Comment by bmaciag** [comment]
Usually badges.json was also updated ;)

**Comment by jung-thomas** [comment]
Yes but we have a secret item this week and publishing the badges.json would give it away.  ;)

**Comment by bmaciag** [comment]
But now its in ;)
