### ISSUE TITLE
ShowcaseBadges - Top 5

### ISSUE THREAD

**Issue by ruthiel** [SAP-samples/sap-community-activity-badges#9]
Hey Thomas,

Just wanted to drop you a quick thank you for sharing this cool functionality! 
I gave it a shot and, well, I did get it to work. But there's a little hiccup – the top 5 badges aren't showing up like they should. It looks like they're just randomly selected from all the badges I've got.

I have only three selected badges:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/17528112/9d4f2282-cc18-425d-a54e-3843c01274f6)

What I've got from the url is:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/17528112/213e2293-ec27-496f-9bdc-7c39b96132e5)

**Comment by jung-thomas** [comment]
What's your community ID - I'll have a look at it.

**Comment by ruthiel** [comment]
> What's your community ID - I'll have a look at it.

ruthiel

**Comment by jung-thomas** [comment]
>the top 5 badges aren't showing up like they should. It looks like they're just randomly selected from all the badges I've got

I'm a little confused. Doesn't seem to be the case.  The Community is displaying these same badges that the Showcase project is showing:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/12159356/f619b817-afab-4c10-beed-77f675c0ad30)

In fact these are your five most recently assigned badges according to your community profile as well:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/12159356/e7878bf3-45a9-4f77-87b9-afd5676725ed)

That all matches exactly to the Showcase:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/12159356/efd7f8f2-f2e0-4f18-998c-622319465134)

**Comment by jung-thomas** [comment]
I see you said you have three selected badges:

> I have only three selected badges

But that doesn't seem to be reflected in your public profile on the SAP Community itself (see above screenshots).  In fact those three badges are from the Dev Challenge and they don't show on this profile that you've even earned those.  Are you sure that you are updating the same profile - maybe you have multiple?  But this project is just reading the Community APIs and using what it returns and that seems to be all in sync for the profile ID you gave me.
https://people.sap.com/ruthiel#reputation

**Comment by ruthiel** [comment]
Hello Thomas,

> Are you sure that you are updating the same profile - maybe you have multiple? But this project is just reading the Community APIs and using what it returns and that seems to be all in sync for the profile ID you gave me. https://people.sap.com/ruthiel#reputation

You're completely correct! 
I was unaware of another account being linked to my SAP account. That was my oversight, and now I see it clearly:
![image](https://github.com/SAP-samples/sap-community-activity-badges/assets/17528112/61c7c93d-23a4-46b4-a343-0daeaab08b02)

Thank you for your help!
